services:

  webapp:
    image: dronahq/self-hosted:3.1.4-stable
    platform: linux/amd64
    container_name: dronahq-self-hosted-webapp
    restart: always
    volumes:
      - ./dronahq.env:/app/.env:ro
      - ./storage/files:/app/files:rw
      - ./storage/private:/app/private:rw
    ports:
      - 8080:8080

  mysqldb:
    image: mysql:8.0.36-oracle
    platform: linux
    container_name: dronahq-self-hosted-mysqldb
    restart: always
    env_file: dronahq.env
    command: --log-bin-trust-function-creators=1
    volumes:
      - ./init/mysql-init.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - ./storage/mysql:/var/lib/mysql
      - ./init/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    ports:
      - 3306:3306

  mongodb:
    image: mongo:5.0.11
    platform: linux
    container_name: dronahq-self-hosted-mongodb
    restart: always
    env_file: dronahq.env
    volumes:
      - ./init/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - ./init/mongo-init.dump:/mongo-init.dump
      - ./storage/mongodb:/data/db
    ports:
      - 27017:27017

  webserver:
    image: nginx
    platform: linux
    container_name: dronahq-self-hosted-webserver
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./storage/certbot/www:/var/www/certbot/:ro
      - ./storage/certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - 80:80
      - 443:443
