#!/usr/bin/env bash
# NB: local trial script has to be self-contained
# See https://sipb.mit.edu/doc/safe-shell/
set -euf -o pipefail

export DRONAHQ_LICENSE_URL="https://license.dronahq.com"

if [[ "$OSTYPE" == "linux-gnu" ]]; then
  export MAYBE_SUDO="sudo"
else
  export MAYBE_SUDO=""
fi

if [ -t 1 ]; then
  export NORMAL="$(tput sgr0)"
  export RED="$(tput setaf 1)"
  export GREEN="$(tput setaf 2)"
  export MAGENTA="$(tput setaf 5)"
  export CYAN="$(tput setaf 6)"
  export WHITE="$(tput setaf 7)"
  export BOLD="$(tput bold)"
else
  export NORMAL=""
  export RED=""
  export GREEN=""
  export MAGENTA=""
  export CYAN=""
  export WHITE=""
  export BOLD=""
fi

error_exit() {
  echo ''
  echo "${RED}${BOLD}ERROR${NORMAL}${BOLD}: $1${NORMAL}"
  shift
  while [ "$#" -gt "0" ]; do
    echo " - $1"
    shift
  done
  exit 1
}

log_step() {
  echo ''
  echo "${GREEN}${BOLD}INFO${NORMAL}${BOLD}: $1${NORMAL}"
  shift
  while [ "$#" -gt "0" ]; do
    echo " - $1"
    shift
  done
}

log_warn() {
  echo ''
  echo "${CYAN}${BOLD}WARNING${NORMAL}${BOLD}: $1${NORMAL}"
  shift
  while [ "$#" -gt "0" ]; do
    echo " - $1"
    shift
  done
}

export DISTRO=$( (lsb_release -ds || cat /etc/*release || uname -om) 2>/dev/null | head -n1)

command_present() {
  type "$1" >/dev/null 2>&1
}

# cleaning directory

log_step "cleaning directory..."

if [ -f ./dronahq.env ]; then
  log_step 'found a partial install, cleaning it up...'
  mv dronahq.env dronahq.env.$(date +"%Y-%m-%d_%H-%M-%S")
fi

if [ -d "storage" ]; then
  log_step 'cleaning `storage`...'
  $MAYBE_SUDO mv storage storage-$(date +"%Y-%m-%d_%H-%M-%S")
fi

# generating environment

log_step "generating environment..."

if [ -f ./dronahq.env ]; then
  mv dronahq.env dronahq.env.$(date +"%Y-%m-%d_%H-%M-%S")
fi

echo "# DronaHQ Environment File" >dronahq.env
echo "" >>dronahq.env
echo "BUILDER_URL='http://localhost'" >>dronahq.env
echo "" >>dronahq.env
echo "MYSQL_HOST='<MYSQL HOST>'" >>dronahq.env
echo "MYSQL_USER='<MYSQL USER>'" >>dronahq.env
echo "MYSQL_PASSWORD='<MYSQL PASSWORD>'" >>dronahq.env
echo "MYSQL_DATABASE='db5x'" >>dronahq.env
echo "" >>dronahq.env
echo "MONGODB_HOST='<MONGO HOST>'" >>dronahq.env
echo "MONGODB_USER='<MONGO USER>'" >>dronahq.env
echo "MONGODB_PASSWORD='<MONGO PASSWORD>'" >>dronahq.env
echo "MONGODB_DATABASE='db5x_studio'" >>dronahq.env
echo "" >>dronahq.env
echo "LICENSE_KEY='<DRONAHQ LICENSE KEY>'" >>dronahq.env
echo "" >>dronahq.env

log_step "Hurray ! Your setup is done."
echo ""
echo "Now you can add your database credentials and DronaHQ License Key in 'dronahq.env' file."
echo ""
echo "Then run following command to start DronaHQ."
echo ""
echo "'sudo docker-compose up -d'"
echo ""
echo "It can take upto 5 minutes to make your installation ready to use."
echo ""
